### ISSUE TITLE
sha256sum error while running playbook

### ISSUE THREAD

**Issue by af** [jlund/mazer-rackham#2]
Hi, 
Thanks for this repo, it's been a great guide to getting started with Ansible! One problem I encountered is that my version of Ansible (1.2.2) seems to throw an error when executing the nginx, ruby, and ruby-falcon roles. I managed to get around this by commenting out the `sha256sum=...` lines in the corresponding main.yml files. Not sure if I'm using the wrong version of ansible or what, but would be good to have note of that in the Readme.

Below is the output I get with one of the errors:

```
TASK: [Download the Nginx source code] ****************************************
failed: [192.168.222.111] => {"failed": true, "item": ""}
msg: unsupported parameter for module: sha256sum

FATAL: all hosts have already failed -- aborting
```

**Comment by af** [comment]
Ah, just noticed that sha256sum was added for Ansible 1.3 (ie. the latest dev version): http://www.ansibleworks.com/docs/modules.html/#id200

So maybe that could be noted in the Readme.

**Comment by jlund** [comment]
Thanks! I really appreciate your feedback, and I'm glad that the repo has been helpful.
