### ISSUE TITLE
ansible.inventory_path

### ISSUE THREAD

**Issue by rgarrigue** [jlund/mazer-rackham#4]
I'm giving a shot to ansible after seing it in the Vagrant provisionner and reading your "Ansible/Salt comparison" article. Thanks about that, very insightful. 

One issue in your Vagrantfile 
    ansible provisioner:
    \* The following settings shouldn't exist: inventory_file
At leat for vagrant 1.3.4 over Win 7, it's ansible.inventory_path.

And while I'm at it, your "Testing this playbook" could be clearer regarding ansible. Sadly their website isn't as clear as vagrant's !

**Comment by jlund** [comment]
I updated the Vagrantfile and added a few new steps to the README.

Thank you very much for your feedback! I'm glad that the article was helpful.
